[tool.mypy]
strict = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_any_generics = true
no_implicit_optional = true
strict_equality = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true

[tool.coverage.run]
parallel = true
data_file = "coverage/.coverage"

source = [
    "tests",
    "reddit_fetch.py",
    "app.py"
]

[tool.coverage.report]
show_missing = true
sort = "-Cover"

[tool.coverage.html]
show_contexts = true
