"""Initial migration

Revision ID: 2316271a80b5
Revises:
Create Date: 2025-04-18 20:23:03.217119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2316271a80b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sentiment_data',
        sa.Column('index', sa.Integer(), nullable=True),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('domain', sa.String(), nullable=True),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('coins', sa.String(), nullable=True),
        sa.Column('published_at', sa.DateTime(), nullable=True),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('sentiment', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentiment_data')
    # ### end Alembic commands ###
