"""Add indices

Revision ID: 5688e2683766
Revises: 2316271a80b5
Create Date: 2025-04-18 20:23:55.565351

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5688e2683766'
down_revision: Union[str, None] = '2316271a80b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_coins', 'sentiment_data', ['coins'], unique=False)
    op.create_index('idx_published_at', 'sentiment_data', ['published_at'], unique=False)
    op.create_index('idx_sentiment', 'sentiment_data', ['sentiment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sentiment', table_name='sentiment_data')
    op.drop_index('idx_published_at', table_name='sentiment_data')
    op.drop_index('idx_coins', table_name='sentiment_data')
    # ### end Alembic commands ###
